name: nodejs CI

on:
  push:
    branches:
      - main
    paths:
      - '**.js'         # Trigger only on JavaScript file changes
      - 'package.json'  # Trigger when package.json changes
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci # Faster and avoids redundant checks

    - name: Run tests
      run: npm test # Add test scripts instead of starting the app directly

    - name: Start application (only on push)
      if: github.event_name == 'push'
      run: npm start
